name: Build & Release 
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:  
  build:      
    name: Build & Release
    runs-on: macos-latest 

    steps:
        #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

        #2 Get Latest Tag
      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag -l --sort=-committerdate | head -n1)
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          echo "Latest Tag: $latest_tag"
          echo ${{ env.LATEST_TAG }} 

        #3 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: gradle

        #4 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true

        #5 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

        #6 Setup Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties
        
       #7 Building APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi

        #8 Upload Artifacts
      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release.apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: app-armeabi-v7a-release.apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-x86_64-release.apk
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk

        #9 Upload to Latest Tag
      - name: Upload to Latest Tag
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh release upload ${{ env.LATEST_TAG }} \
          build/app/outputs/flutter-apk/app-arm64-v8a-release.apk \
          build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk \
          build/app/outputs/flutter-apk/app-x86_64-release.apk \
          --clobber